"""Security test payloads."""

from .sql_injection import (
    ALL_SQLI_PAYLOADS,
    CLASSIC_SQLI,
    UNION_SQLI,
    ERROR_SQLI,
    TIME_SQLI,
    BOOLEAN_SQLI,
    NOSQL_INJECTION,
    SQL_ERROR_SIGNATURES,
)

from .xss import (
    ALL_XSS_PAYLOADS,
    BASIC_XSS,
    EVENT_XSS,
    ENCODED_XSS,
    BYPASS_XSS,
    TEMPLATE_INJECTION,
    XSS_CANARIES,
)

from .directory_traversal import (
    COMMON_LFI_PAYLOADS,
    LINUX_SENSITIVE_FILES,
    WINDOWS_SENSITIVE_FILES,
    WEB_CONFIG_FILES,
    PHP_WRAPPERS,
    FILE_READ_SIGNATURES,
    generate_traversal_payloads,
)

from .wordpress import (
    WP_SENSITIVE_PATHS,
    VULNERABLE_PLUGINS,
    XMLRPC_PAYLOADS,
    COMMON_WP_USERNAMES,
    WP_REST_ENDPOINTS,
    WP_VERSION_PATTERNS,
    WP_SIGNATURES,
    generate_plugin_paths,
)

from .smtp_injection import (
    ALL_SMTP_PAYLOADS,
    SMTP_CRLF_INJECTION,
    SUBJECT_INJECTION,
    EMAIL_MANIPULATION,
    BODY_INJECTION,
    UNICODE_CRLF_VARIANTS,
)

from .business_logic import (
    ALL_BUSINESS_LOGIC_PAYLOADS,
    PRICE_MANIPULATION,
    QUANTITY_MANIPULATION,
    COUPON_ABUSE,
    WORKFLOW_BYPASS,
    PRIVILEGE_ESCALATION,
    TIME_MANIPULATION,
    REFERRAL_ABUSE,
)

from .cache_poisoning import (
    ALL_CACHE_POISON_PAYLOADS,
    CACHE_UNKEYED_HEADERS,
    CACHE_POISON_HEADERS,
    CDN_CACHE_POISON,
    CACHE_DECEPTION_PATHS,
    PARAMETER_CLOAKING,
)

from .dom_xss import (
    ALL_DOM_XSS_PAYLOADS,
    DOM_LOCATION_XSS,
    DOM_HASH_XSS,
    STORAGE_XSS,
    POSTMESSAGE_XSS,
    ANGULAR_XSS,
    REACT_XSS,
    VUE_XSS,
    JQUERY_XSS,
)

from .file_upload import (
    ALL_FILE_UPLOAD_PAYLOADS,
    EXECUTABLE_EXTENSIONS,
    MIME_SPOOF,
    DOUBLE_EXTENSION,
    NULL_BYTE_PAYLOADS,
    POLYGLOT_FILES,
    SVG_XSS_PAYLOADS,
    HTACCESS_PAYLOADS,
)

from .ldap_injection import (
    ALL_LDAP_PAYLOADS,
    LDAP_INJECTION_BASIC,
    LDAP_AUTH_BYPASS,
    LDAP_FILTER_BYPASS,
    ACTIVE_DIRECTORY_INJECTION,
    UNICODE_LDAP_BYPASS,
)

from .race_conditions import (
    ALL_RACE_PAYLOADS,
    COUPON_RACE_PAYLOADS,
    BALANCE_RACE_PAYLOADS,
    FILE_TOCTOU,
    SESSION_RACE,
    OTP_RACE,
    RACE_THREAD_RECOMMENDATIONS,
)

from .request_smuggling import (
    ALL_SMUGGLING_PAYLOADS,
    CL_TE_PAYLOADS,
    TE_CL_PAYLOADS,
    TE_OBFUSCATION,
    H2_DOWNGRADE_SMUGGLING,
    WEBSOCKET_SMUGGLING,
)

from .ssi import (
    ALL_SSI_PAYLOADS,
    SSI_COMMAND_EXEC,
    SSI_FILE_INCLUDE,
    SSI_VARIABLE_EXPOSURE,
    SSI_CONFIG_DIRECTIVES,
    NGINX_SSI,
    IIS_SSI,
)

from .xpath_injection import (
    ALL_XPATH_PAYLOADS,
    XPATH_AUTH_BYPASS,
    XPATH_LOGICAL,
    XPATH_TRAVERSAL,
    XPATH_2_FUNCTIONS,
    XPATH_BOOLEAN_BLIND,
)

from .oauth import (
    OAUTH_REDIRECT_URI,
    OAUTH_STATE,
    OAUTH_PKCE,
    OAUTH_SCOPE,
    OAUTH_TOKEN,
)

from .hpp import (
    HPP_BASIC,
    HPP_ARRAY,
    HPP_WAF_BYPASS,
    HPP_AUTH_BYPASS,
)

from .websocket import (
    WEBSOCKET_CROSS_ORIGIN,
    WEBSOCKET_XSS,
    WEBSOCKET_AUTH_BYPASS,
    WEBSOCKET_MESSAGE_INJECTION,
)

from .llm_emerging import (
    # Skeleton Key
    SKELETON_KEY_PAYLOADS,
    SKELETON_KEY_SIGNATURES,
    # Many-Shot
    MANY_SHOT_PAYLOADS,
    # Visual/Audio Injection
    VISUAL_INJECTION_PAYLOADS,
    AUDIO_INJECTION_PAYLOADS,
    # Agent Hijacking
    AGENT_WORKFLOW_HIJACK_PAYLOADS,
    # Guardrail Bypass
    GUARDRAIL_BYPASS_PAYLOADS,
    # System Prompt Reconstruction
    SYSTEM_PROMPT_RECONSTRUCTION_PAYLOADS,
    # Prefilling
    PREFILLING_ATTACK_PAYLOADS,
    # Function Injection
    FUNCTION_PARAMETER_INJECTION_PAYLOADS,
    # Reasoning Manipulation
    REASONING_TRACE_MANIPULATION_PAYLOADS,
    # Tool Result Injection
    TOOL_RESULT_INJECTION_PAYLOADS,
    # Context Smuggling
    CONTEXT_WINDOW_SMUGGLING_PAYLOADS,
    # Boundary Confusion
    INSTRUCTION_BOUNDARY_CONFUSION_PAYLOADS,
    # Jailbreak Transfer
    JAILBREAK_TRANSFER_PAYLOADS,
    # Fine-tuning Poisoning
    FINETUNING_POISONING_PAYLOADS,
    # Prompt Caching
    PROMPT_CACHING_ATTACK_PAYLOADS,
    # Constitutional AI
    CONSTITUTIONAL_AI_BYPASS_PAYLOADS,
    # Model Merging
    MODEL_MERGING_VULNERABILITY_PAYLOADS,
    # Quantization
    QUANTIZATION_VULNERABILITY_PAYLOADS,
    # Speculative Decoding
    SPECULATIVE_DECODING_PAYLOADS,
    # Aggregates
    ALL_EMERGING_PAYLOADS,
    EMERGING_SUCCESS_SIGNATURES,
)

__all__ = [
    # SQL Injection
    "ALL_SQLI_PAYLOADS",
    "CLASSIC_SQLI",
    "UNION_SQLI",
    "ERROR_SQLI",
    "TIME_SQLI",
    "BOOLEAN_SQLI",
    "NOSQL_INJECTION",
    "SQL_ERROR_SIGNATURES",
    # XSS
    "ALL_XSS_PAYLOADS",
    "BASIC_XSS",
    "EVENT_XSS",
    "ENCODED_XSS",
    "BYPASS_XSS",
    "TEMPLATE_INJECTION",
    "XSS_CANARIES",
    # Directory Traversal
    "COMMON_LFI_PAYLOADS",
    "LINUX_SENSITIVE_FILES",
    "WINDOWS_SENSITIVE_FILES",
    "WEB_CONFIG_FILES",
    "PHP_WRAPPERS",
    "FILE_READ_SIGNATURES",
    "generate_traversal_payloads",
    # WordPress
    "WP_SENSITIVE_PATHS",
    "VULNERABLE_PLUGINS",
    "XMLRPC_PAYLOADS",
    "COMMON_WP_USERNAMES",
    "WP_REST_ENDPOINTS",
    "WP_VERSION_PATTERNS",
    "WP_SIGNATURES",
    "generate_plugin_paths",
    # SMTP Injection
    "ALL_SMTP_PAYLOADS",
    "SMTP_CRLF_INJECTION",
    "SUBJECT_INJECTION",
    "EMAIL_MANIPULATION",
    "BODY_INJECTION",
    "UNICODE_CRLF_VARIANTS",
    # Business Logic
    "ALL_BUSINESS_LOGIC_PAYLOADS",
    "PRICE_MANIPULATION",
    "QUANTITY_MANIPULATION",
    "COUPON_ABUSE",
    "WORKFLOW_BYPASS",
    "PRIVILEGE_ESCALATION",
    "TIME_MANIPULATION",
    "REFERRAL_ABUSE",
    # Cache Poisoning
    "ALL_CACHE_POISON_PAYLOADS",
    "CACHE_UNKEYED_HEADERS",
    "CACHE_POISON_HEADERS",
    "CDN_CACHE_POISON",
    "CACHE_DECEPTION_PATHS",
    "PARAMETER_CLOAKING",
    # DOM XSS
    "ALL_DOM_XSS_PAYLOADS",
    "DOM_LOCATION_XSS",
    "DOM_HASH_XSS",
    "STORAGE_XSS",
    "POSTMESSAGE_XSS",
    "ANGULAR_XSS",
    "REACT_XSS",
    "VUE_XSS",
    "JQUERY_XSS",
    # File Upload
    "ALL_FILE_UPLOAD_PAYLOADS",
    "EXECUTABLE_EXTENSIONS",
    "MIME_SPOOF",
    "DOUBLE_EXTENSION",
    "NULL_BYTE_PAYLOADS",
    "POLYGLOT_FILES",
    "SVG_XSS_PAYLOADS",
    "HTACCESS_PAYLOADS",
    # LDAP Injection
    "ALL_LDAP_PAYLOADS",
    "LDAP_INJECTION_BASIC",
    "LDAP_AUTH_BYPASS",
    "LDAP_FILTER_BYPASS",
    "ACTIVE_DIRECTORY_INJECTION",
    "UNICODE_LDAP_BYPASS",
    # Race Conditions
    "ALL_RACE_PAYLOADS",
    "COUPON_RACE_PAYLOADS",
    "BALANCE_RACE_PAYLOADS",
    "FILE_TOCTOU",
    "SESSION_RACE",
    "OTP_RACE",
    "RACE_THREAD_RECOMMENDATIONS",
    # Request Smuggling
    "ALL_SMUGGLING_PAYLOADS",
    "CL_TE_PAYLOADS",
    "TE_CL_PAYLOADS",
    "TE_OBFUSCATION",
    "H2_DOWNGRADE_SMUGGLING",
    "WEBSOCKET_SMUGGLING",
    # SSI
    "ALL_SSI_PAYLOADS",
    "SSI_COMMAND_EXEC",
    "SSI_FILE_INCLUDE",
    "SSI_VARIABLE_EXPOSURE",
    "SSI_CONFIG_DIRECTIVES",
    "NGINX_SSI",
    "IIS_SSI",
    # XPath Injection
    "ALL_XPATH_PAYLOADS",
    "XPATH_AUTH_BYPASS",
    "XPATH_LOGICAL",
    "XPATH_TRAVERSAL",
    "XPATH_2_FUNCTIONS",
    "XPATH_BOOLEAN_BLIND",
    # OAuth
    "OAUTH_REDIRECT_URI",
    "OAUTH_STATE",
    "OAUTH_PKCE",
    "OAUTH_SCOPE",
    "OAUTH_TOKEN",
    # HPP
    "HPP_BASIC",
    "HPP_ARRAY",
    "HPP_WAF_BYPASS",
    "HPP_AUTH_BYPASS",
    # WebSocket
    "WEBSOCKET_CROSS_ORIGIN",
    "WEBSOCKET_XSS",
    "WEBSOCKET_AUTH_BYPASS",
    "WEBSOCKET_MESSAGE_INJECTION",
    # LLM Emerging (2024-2025)
    "SKELETON_KEY_PAYLOADS",
    "SKELETON_KEY_SIGNATURES",
    "MANY_SHOT_PAYLOADS",
    "VISUAL_INJECTION_PAYLOADS",
    "AUDIO_INJECTION_PAYLOADS",
    "AGENT_WORKFLOW_HIJACK_PAYLOADS",
    "GUARDRAIL_BYPASS_PAYLOADS",
    "SYSTEM_PROMPT_RECONSTRUCTION_PAYLOADS",
    "PREFILLING_ATTACK_PAYLOADS",
    "FUNCTION_PARAMETER_INJECTION_PAYLOADS",
    "REASONING_TRACE_MANIPULATION_PAYLOADS",
    "TOOL_RESULT_INJECTION_PAYLOADS",
    "CONTEXT_WINDOW_SMUGGLING_PAYLOADS",
    "INSTRUCTION_BOUNDARY_CONFUSION_PAYLOADS",
    "JAILBREAK_TRANSFER_PAYLOADS",
    "FINETUNING_POISONING_PAYLOADS",
    "PROMPT_CACHING_ATTACK_PAYLOADS",
    "CONSTITUTIONAL_AI_BYPASS_PAYLOADS",
    "MODEL_MERGING_VULNERABILITY_PAYLOADS",
    "QUANTIZATION_VULNERABILITY_PAYLOADS",
    "SPECULATIVE_DECODING_PAYLOADS",
    "ALL_EMERGING_PAYLOADS",
    "EMERGING_SUCCESS_SIGNATURES",
]
